const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const M=require('../assets/fleet-model.js');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const auth=fs.readFileSync(path.join(__dirname,'../auth.js'),'utf8');
const rules=fs.readFileSync(path.join(__dirname,'../firestore.rules'),'utf8');
const ui=fs.readFileSync(path.join(__dirname,'../assets/fleet-views.js'),'utf8');
const now='2026-10-08T09:00:00Z';
const add=(list,id,tail,status='SERVICEABLE',reason='',since='2026-10-08',platform='shahak')=>M.upsertAircraft(list,{tail,status,reason,since},platform,now,()=>id);
test('aircraft inventory is platform-scoped, editable, archived non-destructively',()=>{
 let rows=[];
 rows=add(rows,'a01','01');rows=add(rows,'a02','02');rows=add(rows,'a03','03','UNSERVICEABLE','Engine maintenance','2026-10-05');rows=add(rows,'a04','04');
 assert.deepEqual(M.count(rows,'shahak').serviceable,3);
 assert.deepEqual(M.count(rows,'shahak').unserviceable,1);
 assert.equal(M.count(rows,'aerostar').total,0);
 assert.equal(rows.find(x=>x.id==='a03').reason,'Engine maintenance');
 assert.equal(rows.find(x=>x.id==='a03').since,'2026-10-05');
 rows=M.upsertAircraft(rows,{id:'a03',tail:'03',status:'SERVICEABLE',since:'2026-10-08'},'shahak',now);
 assert.equal(M.count(rows,'shahak').serviceable,4);
 assert.equal(rows.find(x=>x.id==='a03').history.length,2);
 rows=M.archiveAircraft(rows,'a04','shahak',now);
 assert.equal(M.count(rows,'shahak').total,3);
 assert.ok(rows.find(x=>x.id==='a04').archivedAt);
 assert.throws(()=>M.archiveAircraft(rows,'a04','aerostar'));
});
test('unserviceability requires dated reason, prohibits duplicate identifiers and malformed dates',()=>{
 let rows=add([],'a01','01');
 assert.throws(()=>add(rows,'a02','01'),/already exists/);
 assert.throws(()=>add(rows,'a02','02','UNSERVICEABLE','', '2026-10-08'),/reason/);
 assert.throws(()=>add(rows,'a02','02','UNSERVICEABLE','Fault','2026-02-31'),/date/);
 assert.throws(()=>add(rows,'a02','02','SERVICEABLE','','2026-02-31'),/date/);
 assert.equal(M.dateValid('2026-10-08'),true);
 assert.equal(M.clockValid('23:59'),true);
 assert.equal(M.clockValid('25:00'),false);
});
test('scheduled flights can only select serviceable aircraft and valid assigned people',()=>{
 let planes=add([],'a01','01');
 planes=add(planes,'a03','03','UNSERVICEABLE','Needs propeller','2026-10-03');
 const ids={trainees:['t1'],instructors:['i1']};
 const base={time:'09:30',aircraftId:'a01',traineeId:'t1',traineeName:'Pilot 1',instructorId:'i1',instructorName:'Coach',syllabus:'Circuits',mode:'INSTRUCTED'};
 assert.throws(()=>M.upsertSortie([],{...base,aircraftId:'a03'},planes,'shahak','2026-10-08',ids),/not serviceable/);
 assert.throws(()=>M.upsertSortie([],{...base,traineeId:'else'},planes,'shahak','2026-10-08',ids),/assigned to this course/);
 assert.throws(()=>M.upsertSortie([],{...base,time:'25:00'},planes,'shahak','2026-10-08',ids),/valid flight date and time/);
 let board=M.upsertSortie([],{...base},planes,'shahak','2026-10-08',ids,now,()=> 'flight1');
 assert.equal(board.length,1);assert.equal(board[0].tail,'01');
 assert.throws(()=>M.upsertSortie(board,{...base},planes,'shahak','2026-10-08',ids,now,()=> 'flight2'),/already scheduled/);
 assert.equal(M.flightIssues(board[0],planes,'shahak'),'');
 planes=M.upsertAircraft(planes,{id:'a01',tail:'01',status:'UNSERVICEABLE',reason:'Fuel system',since:'2026-10-08'},'shahak',now);
 assert.match(M.flightIssues(board[0],planes,'shahak'),/Fuel system/);
 assert.equal(board[0].aircraftId,'a01');
 assert.throws(()=>M.upsertSortie(board,{...base,id:'flight1'},planes,'shahak','2026-10-08',ids),/not serviceable/);
});
test('User Management Duty Trainee role has operational permissions without structural admin',()=>{
 assert.ok(auth.includes("duty_trainee:Object.freeze({"));
 const duty=auth.match(/duty_trainee:Object.freeze\(\{[\s\S]*?capabilities:Object.freeze\(\[([^\]]+)\]\)/);
 assert.ok(duty);
 for(const cap of ['operations.daily.write','operations.flightBoard.write','operations.solo.write','fleet.serviceability.write'])assert.ok(duty[1].includes(cap));
 for(const cap of ['users.manage','roster.manage','courses.create','packages.manageGlobal'])assert.ok(!duty[1].includes(cap));
 assert.ok(auth.includes("'Daily flight operations'"));
 assert.ok(auth.includes("'Duty Trainee':'חניך תורן'"));
 assert.ok(rules.includes("'duty_trainee'"));
 assert.ok(html.includes("isDutyTraineeAssigned(courseKey=currentCourseId)"));
 assert.ok(html.includes("isDutyTraineeAssigned(courseKey(record))"));
 assert.ok(html.includes("if(!flympusCan('operations.daily.write'))"));
 assert.ok(html.includes("if(!flympusCan('operations.flightBoard.write'))"));
});
test('Fleet and daily board are accessible per course from Home; refresh and theme parity remain intact',()=>{
 for(const item of ["case'fleet'",'bindFleet()','bindDailyFlightBoard()',
 'appScreenIds=new Set(','getFleetAircraft()','getDailyFlightBoard()','courseScopedKey(base)','flightBoardEditId',
 'window.FLYMPUS_FLEET_VIEW?.home?.(currentFleetContext())','courseFlightScheduleHtml(date)'])assert.ok(html.includes(item),item);
 assert.ok(ui.includes("M.flightIssues(f,c.fleet,c.platformId)"));
 assert.ok(ui.includes("const available=M.active(c.fleet,c.platformId).filter(x=>x.status===M.AVAILABLE)"));
 assert.ok(html.includes('html[data-flympus-theme="dark"]')||fs.readFileSync(path.join(__dirname,'../assets/fleet-operations.css'),'utf8').includes('html[data-flympus-theme="dark"]'));
 assert.ok(fs.readFileSync(path.join(__dirname,'../assets/fleet-operations.css'),'utf8').includes('@media(max-width:560px)'));
});

test('Fleet Home uses real aircraft rows and places the inventory table in the primary Home grid',()=>{
 const vm=require('node:vm');
 const context={window:{FLYMPUS_FLEET_MODEL:M,FLYMPUS_FLEET_LANGUAGE:()=> 'en'}};
 vm.runInNewContext(ui,context,{filename:'fleet-views.js'});
 const V=context.window.FLYMPUS_FLEET_VIEW;
 const fleet=[...add([],'a01','01'),];
 const down=add(fleet,'a02','02','UNSERVICEABLE','Hydraulic inspection','2026-10-07');
 const ctx={fleet:down,platformId:'shahak',platformLabel:'Aerostar',courseLabel:'Training',today:'2026-10-08',canWrite:true};
 const home=V.home(ctx),detail=V.fleet(ctx),empty=V.home({...ctx,fleet:[]});
 assert.match(home,/fleetHomeTable/);
 assert.match(home,/01/);
 assert.match(home,/02/);
 assert.match(home,/Hydraulic inspection/);
 assert.match(home,/Unserviceable/);
 assert.match(home,/1<\/b> \/ 2/);
 assert.match(empty,/No aircraft registered/);
 assert.doesNotMatch(empty,/Hydraulic inspection/);
 assert.match(detail,/fleetInventoryTable/);
 assert.match(detail,/data-fleet-add/);
 assert.match(detail,/id="fleetEditorPanel" hidden/);
 assert.match(detail,/data-fleet-reason-field/);
 assert.ok(detail.indexOf('fleetInventoryTable')<detail.indexOf('id="fleetEditorPanel"'));
 const editing=V.fleet({...ctx,editId:'a02'});
 assert.match(editing,/id="fleetEditorPanel"/);
 assert.doesNotMatch(editing,/id="fleetEditorPanel" hidden/);
 const readonly=V.fleet({...ctx,canWrite:false});
 assert.doesNotMatch(readonly,/data-fleet-edit=/);
 assert.doesNotMatch(readonly,/fleetAircraftForm/);
 assert.ok(html.indexOf("FLYMPUS_FLEET_VIEW?.home?.(currentFleetContext())")>html.indexOf("'<section class=\"homePrimaryGrid\">'"));
 assert.ok(html.indexOf("<h2>Course Pulse</h2>")<html.indexOf("FLYMPUS_FLEET_VIEW?.home?.(currentFleetContext())"));
 assert.equal((html.match(/FLYMPUS_FLEET_VIEW\?\.home\?\.\(currentFleetContext\(\)\)/g)||[]).length,1);
 assert.ok(!html.includes("'<div class=\"homeTaskStrip\">'"),"Home no longer repeats quick actions");
 assert.ok(html.includes("holder.hidden=!down"),'Unavailable reason is only shown when relevant');
});
test('Serviceability history captures optional signed-in operator without changing old data',()=>{
 let aircraft=M.upsertAircraft([],{tail:'03',status:'SERVICEABLE',since:'2026-10-08'},'shahak',now,()=> 'a03','Instructor A');
 assert.equal(aircraft[0].history[0].recordedBy,'Instructor A');
 aircraft=M.upsertAircraft(aircraft,{id:'a03',tail:'03',status:'UNSERVICEABLE',reason:'Inspection',since:'2026-10-08'},'shahak',now,()=> 'unused','Duty Trainee');
 assert.deepEqual(aircraft[0].history.map(h=>h.recordedBy),['Instructor A','Duty Trainee']);
});


test('Fleet names replace old module headings while Serviceability remains the actual aircraft status',()=>{
 const vm=require('node:vm');
 const context={window:{FLYMPUS_FLEET_MODEL:M,FLYMPUS_FLEET_LANGUAGE:()=> 'en'}};
 vm.runInNewContext(ui,context,{filename:'fleet-views.js'});
 const V=context.window.FLYMPUS_FLEET_VIEW;
 const ctx={fleet:add([],'aircraft-1','01'),flights:[],platformId:'shahak',platformLabel:'Shahak',courseLabel:'EP',today:'2026-10-08',date:'2026-10-08',trainees:[],instructors:[],syllabi:['Circuits'],canWrite:true};
 assert.match(V.home(ctx),/<h2>Fleet<\/h2>/);
 assert.match(V.fleet(ctx),/<h1 class="pageTitle">Fleet<\/h1>/);
 assert.match(V.fleet(ctx),/Serviceability/);
 assert.doesNotMatch(V.fleet(ctx),/<h1 class="pageTitle">Aircraft Serviceability<\/h1>/);
 assert.match(V.schedule(ctx),/data-go="fleet"/);
 assert.match(html,/<h3>Fleet<\/h3>/);
 assert.doesNotMatch(html,/<h3>Aircraft Serviceability<\/h3>/);
 assert.ok(html.includes("flympusAccessDenied('Fleet')"));
});
test('Plan opens on the date-specific Daily Flight Plan with separate Planned vs Executed tab',()=>{
 const page=html.slice(html.indexOf('function dailyFlightPlan(){'),html.indexOf('function globalBackControl(){'));
 assert.match(page,/Daily Flight Plan/);
 assert.match(page,/Planned vs Executed/);
 assert.match(page,/data-plan-view="board"/);
 assert.match(page,/data-plan-view="report"/);
 assert.match(page,/id="dailyPlanDate"/);
 assert.ok(page.includes("courseFlightScheduleHtml(date)"));
 assert.ok(page.includes("view==='board'?dailyFlightPlan():plannedVsExecuted()"));
 assert.ok(html.includes("case'planned':html=planWorkspace();break"));
 assert.ok(html.includes("if(state.planView==='report')bindPlanned();else bindDailyFlightBoard()"));
 assert.ok(html.includes("b.dataset.planToday==='true'?{planView:'board',planDate:todayIsoDate()"));
 const homeSource=html.slice(html.indexOf('function home(){'),html.indexOf('function evaluationHistoryViewHtml('));
 assert.match(homeSource, /<h2>Today.*s Plan<\/h2>/);
 assert.ok(homeSource.includes('<span class="homeDateChip">'));
 assert.ok(homeSource.includes('<div class="homePlanRow">'));
 assert.ok(homeSource.includes('<div class="homePlanRow homePlanEmpty">'));
 assert.ok(!homeSource.includes('data-plan-today="true"'),'Home Today Plan must not navigate to Plan');
 assert.ok(!homeSource.includes('homePlanTitleButton'),'Home Today Plan title must not be a button');
 assert.ok(!homeSource.includes('homePlanDateButton'),'Home Today Plan date must not be a button');
 assert.ok(!homeSource.includes('data-go="reports"'),'Course Pulse no longer offers View Reports');
 assert.ok(html.includes("case'reports':html=reports();break"),'Reports navigation remains available');
 assert.ok(!html.includes("courseFlightScheduleHtml(date)+\n '<section class=\"card pvePanel\">"));
});
test('Scheduled sortie accepts optional planned duration and notes without changing serviceability constraints',()=>{
 const fleet=add([],'ac1','01'),allowed={trainees:['trainee1'],instructors:['ip1']};
 const flight={date:'2026-10-08',time:'11:30',mode:'INSTRUCTED',aircraftId:'ac1',traineeId:'trainee1',instructorId:'ip1',instructorName:'IP',traineeName:'EP',syllabus:'Circuits',estimatedMinutes:'35',note:'Winds and circuit work'};
 const result=M.upsertSortie([],flight,fleet,'shahak','2026-10-08',allowed,now,()=> 'sortie1');
 assert.equal(result[0].estimatedMinutes,35);
 assert.equal(result[0].note,'Winds and circuit work');
 const amended=M.upsertSortie(result,{...flight,id:'sortie1',estimatedMinutes:'45',note:'Revised'},fleet,'shahak','2026-10-08',allowed,now);
 assert.equal(amended[0].estimatedMinutes,45);
 assert.equal(amended[0].note,'Revised');
 assert.throws(()=>M.upsertSortie([],{...flight,estimatedMinutes:'721'},fleet,'shahak','2026-10-08',allowed),/duration/);
 assert.throws(()=>M.upsertSortie([],{...flight,estimatedMinutes:'0'},fleet,'shahak','2026-10-08',allowed),/duration/);
 assert.throws(()=>M.upsertSortie([],{...flight,aircraftId:'unknown'},fleet,'shahak','2026-10-08',allowed),/serviceable/);
 assert.ok(html.includes("estimatedMinutes:String(fd.get('estimatedMinutes')||'')"));
 assert.ok(html.includes("note:String(fd.get('note')||'')"));
});
test('Duty trainee can open Plan board, while Fleet and Plan restrictions stay scoped',()=>{
 assert.ok(html.includes("DUTY_ALLOWED_SCREENS=new Set(['home','planned','fleet','preferences'])"));
 assert.ok(html.includes("if(!flympusCan('operations.flightBoard.write'))return;"));
 assert.ok(html.includes("if(!flympusCan('operations.daily.write'))"));
 assert.ok(html.includes("if(!canViewDutyScreen(screen))"));
});
