const fs=require("node:fs");
const vm=require("node:vm");
const assert=require("node:assert/strict");
const storage=()=>{const values=new Map();return{getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key)}};
class ElementStub{
  constructor(){this.innerHTML="";this.textContent="";this.value="";this.dataset={};this.style={};this.classList={add(){},remove(){},toggle(){}}}
  querySelectorAll(){return[]} querySelector(){return null} addEventListener(){} click(){} appendChild(){}
}
const elements=new Map(["#menuBtn","#backdrop","#nav","#content","#drawer","#toast"].map(id=>[id,new ElementStub()]));
const document={querySelector:selector=>elements.get(selector)||null,querySelectorAll:()=>[],createElement:()=>new ElementStub()};
const context={window:{},document,localStorage:storage(),sessionStorage:storage(),console,confirm:()=>true,setTimeout:()=>0,clearTimeout(){},Date,Math,JSON,Number,String,Array,Object,Map,Set,FormData:class{},Blob:class{},URL:{createObjectURL(){return""},revokeObjectURL(){}},location:{},navigator:{}};
context.window=context;vm.createContext(context);
for(const file of ["assets/ep-catalog.js","assets/aerostar-platform.js","assets/ip-catalog.js","assets/technician-catalog.js","assets/training-core.js","assets/ep-lessons-screening.js","assets/ep-lessons-rc-1.js","assets/ep-lessons-rc-2.js","assets/ep-lessons-half.js","assets/ep-lessons-full-day-a.js","assets/ep-lessons-full-day-b.js","assets/ep-lessons-night.js"]){vm.runInContext(fs.readFileSync(file,"utf8"),context,{filename:file})}
const html=fs.readFileSync("index.html","utf8");
assert(html.includes("platformLabels:{rc_simulator:'RC Simulator',rc_model:'Shahak'"),"Shahak must be the default display name for rc_model");
assert(html.includes("catalog.platformLabels=labels"),"Platform renames must persist inside the architecture catalog");
assert(html.includes("internal platform identifier stays stable automatically and is intentionally hidden"),"Platform editor must explain stable hidden IDs");
assert(!html.includes("<span class=\"pill gray\">'+esc(x.id)+'</span>"),"Platform internal IDs must not be shown as user-facing pills");
assert(html.includes("myCoursesPlatformFilter")&&html.includes("myCoursesCountryFilter"),"My Courses must filter by platform and country");
assert(html.includes("myCoursesStatusFilter"),"My Courses must filter by lifecycle status");
assert(html.includes('aria-controls="topCourseDropdown"')&&html.includes('id="topCourseDropdown"'),"Header must contain a real course switcher dropdown");
assert(html.includes(".topCourseDropdown{position:fixed;left:calc(14px + env(safe-area-inset-left));right:calc(14px + env(safe-area-inset-right));width:auto"),"Mobile quick course dropdown must stay inside the viewport on both sides");
assert(html.includes("function positionTopCourseDropdown()"),"Quick course switcher must position its mobile menu below the real header button");
assert(html.includes("if(open)positionTopCourseDropdown()"),"Opening the quick course switcher must position the mobile menu before interaction");
assert(html.includes("<span>Selected course</span>"),"Header switcher must describe the selected course, not an active lifecycle state");
assert(html.includes("function sortCourseSwitcherRows(rows,selectedKey=currentCourseId)"),"Quick course switcher needs deterministic ordering");
assert(html.includes("View all courses →"),"Quick course switcher must link to the full My Courses screen");
assert(!html.includes("if($('#topCourseSwitch'))$('#topCourseSwitch').onclick=()=>go('courses')"),"Top course control must no longer fake a dropdown by navigating directly to My Courses");
assert(html.includes("courseSelectedBadge")&&html.includes("courseStateBadge"),"Selected-course state must be visually separate from course lifecycle status");
assert(html.includes(".myCourseCard.selected{border-color:#2b8bde;box-shadow:0 0 0 3px rgba(43,139,222,.18)"),"Selected course card needs a strong visual frame in addition to the SELECTED badge");
assert(html.includes("function courseLifecycleStatus(record)"),"Course lifecycle status must support Upcoming, In progress and Completed");
assert(html.includes("sectorPlatforms(sector)")&&html.includes("flatMap(x=>sectorPlatforms(x.id))"),"My Courses platform options must come from the architecture platform catalog");
assert(html.includes("function courseSummaryFromMeta(meta)"),"Course summaries must be rebuilt from live architecture metadata");
assert(html.includes("summary:'EP · RC Model · RC Model · New Training · Day · Israel'"),"Built-in summary must preserve separate Phase and Platform slots even when their labels match");
assert(html.includes("myCoursesSectorFilter")&&html.includes("myCoursesPhaseFilter")&&html.includes("myCoursesTrainingFilter")&&html.includes("myCoursesRoleFilter"),"My Courses must expose filters for sector, phase, training type and role");
assert(html.includes("function renderPreservingManagementView(update)"),"Management edit mode needs a view-preserving renderer");
assert(html.includes("overflowAnchor='none'"),"Management Edit must disable native scroll anchoring while the view is rebuilt");
assert(html.includes("anchorSelector='.card,.packageRules,.advancedStepLabel,.personCard,.rosterControls,.trainingStatusStack'"),"Management Edit must preserve a visible content anchor, not only the absolute scrollTop");
assert(html.includes("window.scrollBy(0,delta)"),"Management Edit must compensate for layout-height changes above the viewport");
assert(html.includes("courseTailorEdit'))$('#courseTailorEdit').onclick=()=>renderPreservingManagementView"),"Tailor Edit must preserve the current view");
assert(html.includes("advancedArchitectureEdit'))$('#advancedArchitectureEdit').onclick=()=>renderPreservingManagementView"),"Advanced Edit must preserve the current view");
assert(html.includes("toggleRosterManage').onclick=()=>renderPreservingManagementView"),"Course Roster Manage must preserve the current view");
assert(!html.includes("Restore original Package defaults"),"Bulk Package restore-to-defaults must be removed");
assert(!html.includes("Revert to Package defaults"),"Bulk course revert-to-defaults must be removed");
assert(html.includes(".packageRules>summary>span{font-size:9px;color:#8092a5}"),"Summary helper styling must target only the direct helper span so counts inside titles keep the title font");
const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(match=>match[1]).filter(x=>x.trim());
assert.equal(scripts.length,1);vm.runInContext(scripts[0],context,{filename:"index-inline.js"});
const switcherOrder=vm.runInContext("sortCourseSwitcherRows([{key:'done',course:{startsOn:'2025-01-01'},lifecycle:{id:'COMPLETED'}},{key:'future2',course:{startsOn:'2027-03-01'},lifecycle:{id:'UPCOMING'}},{key:'current',course:{startsOn:'2024-01-01'},lifecycle:{id:'COMPLETED'}},{key:'runOld',course:{startsOn:'2026-01-01'},lifecycle:{id:'IN_PROGRESS'}},{key:'runNew',course:{startsOn:'2026-08-01'},lifecycle:{id:'IN_PROGRESS'}},{key:'future1',course:{startsOn:'2027-01-01'},lifecycle:{id:'UPCOMING'}}],'current').map(x=>x.key).join(',')",context);
assert.equal(switcherOrder,"current,runNew,runOld,future1,future2,done","Quick switcher order must be Selected, In Progress newest first, Upcoming soonest first, then Completed");
assert.match(elements.get("#content").innerHTML,/My Courses/);
assert.match(elements.get("#content").innerHTML,/Aerostar EP Course/);
assert.match(elements.get("#content").innerHTML,/id="myCoursesStatusFilter"/);
assert.match(elements.get("#content").innerHTML,/IN PROGRESS/);
assert.match(elements.get("#content").innerHTML,/SELECTED/);
assert.doesNotMatch(elements.get("#content").innerHTML,/>ACTIVE</,"My Courses must not use ACTIVE to mean the selected course");
assert.match(elements.get("#content").innerHTML,/EP · RC Model · RC Model · New Training · Day · Israel/,"My Courses must show Phase and Platform as separate semantic fields");
assert.match(elements.get("#content").innerHTML,/id="myCoursesPlatformFilter"/);
assert.match(elements.get("#content").innerHTML,/id="myCoursesCountryFilter"/);
assert.match(elements.get("#content").innerHTML,/RC Simulator/);
assert.match(elements.get("#content").innerHTML,/RC Model/);
assert.match(elements.get("#content").innerHTML,/Half Scale Trainer/);
assert.match(elements.get("#content").innerHTML,/Aerostar/);
assert.match(elements.get("#content").innerHTML,/Orbiter 3MP/);
assert.match(elements.get("#content").innerHTML,/id="myCoursesSectorFilter"/);
assert.match(elements.get("#content").innerHTML,/id="myCoursesPhaseFilter"/);
assert.match(elements.get("#content").innerHTML,/id="myCoursesTrainingFilter"/);
assert.match(elements.get("#content").innerHTML,/id="myCoursesRoleFilter"/);
assert.equal(vm.runInContext("instructorAssignedCourses(currentUserId).length",context),1);
vm.runInContext("go('home')",context);assert(elements.get("#content").innerHTML.length>1000,"Home must render");
vm.runInContext(`localStorage.setItem('ct-review-courses',JSON.stringify([{id:'course_multi',name:'Aerostar EP Night 2027',code:'EP-NIGHT-27',summary:'EP · Full Scale · Aerostar · Night',startsOn:'2027-01-10',selection:{courseType:'EP',phaseId:'ep_full',platformId:'aerostar',trainingKind:'new',dayNight:'night',country:'israel'},platformId:'aerostar',programId:'ep_full_night_new'}]));updateCourseMembershipForCourse('EP-NIGHT-27',currentUserId,'INSTRUCTOR',{role:'COURSE_MANAGER',removed:false});state.screen='courses';render()`,context);
assert.match(elements.get("#content").innerHTML,/Aerostar EP Night 2027/);
assert.equal(vm.runInContext("instructorAssignedCourses(currentUserId).length",context),2);
const quickSwitcherHtml=vm.runInContext("topCourseSwitcherItemsHtml()",context);
assert(quickSwitcherHtml.indexOf("Aerostar EP Course")<quickSwitcherHtml.indexOf("Aerostar EP Night 2027"),"Selected course must appear first in the quick switcher");
assert.match(quickSwitcherHtml,/UPCOMING · Course Manager · Starts/);
assert.match(quickSwitcherHtml,/✓ Selected/);
assert.match(elements.get("#content").innerHTML,/UPCOMING/,"Future courses must display Upcoming independently of the selected course");
vm.runInContext("state.myCoursesStatus='UPCOMING';render()",context);
assert.match(elements.get("#content").innerHTML,/Aerostar EP Night 2027/);
assert.doesNotMatch(elements.get("#content").innerHTML,/Aerostar EP Course/);
vm.runInContext("state.myCoursesStatus='ALL';render()",context);
vm.runInContext("state.myCoursesPhase='Full Scale';render()",context);
assert.match(elements.get("#content").innerHTML,/Aerostar EP Night 2027/);
assert.doesNotMatch(elements.get("#content").innerHTML,/Aerostar EP Course/);
assert.match(elements.get("#content").innerHTML,/1 of 2 courses shown/);
vm.runInContext("state.myCoursesPhase='ALL';render()",context);
vm.runInContext("const labels=getPlatformLabels();labels.rc_model='RC Trainer';savePlatformLabels(labels);render()",context);
assert.match(elements.get("#content").innerHTML,/EP · RC Model · RC Trainer · New Training · Day · Israel/,"Edited platform labels must propagate into My Courses immediately");
vm.runInContext("const labels=getPlatformLabels();delete labels.rc_model;savePlatformLabels(labels);render()",context);
assert.equal(vm.runInContext("instructorAssignedCourses('i2').some(x=>courseKey(x)==='EP-NIGHT-27')",context),false);
vm.runInContext("updateCourseMembershipForCourse('EP-NIGHT-27','i2','INSTRUCTOR',{role:'INSTRUCTOR',removed:false})",context);
assert.equal(vm.runInContext("instructorAssignedCourses('i2').some(x=>courseKey(x)==='EP-NIGHT-27')",context),true);
vm.runInContext("switchCourseByKey('EP-NIGHT-27',{render:false});setEvaluations([{id:'multi_eval',flightDate:'2027-01-11',traineeId:'t1',instructorId:'i1',syllabus:'Takeoff',grade:4}])",context);
assert.equal(vm.runInContext("getEvaluations().length",context),1);
vm.runInContext("switchCourseByKey('AEP-26',{render:false,force:true})",context);
assert.equal(vm.runInContext("getEvaluations().some(x=>x.id==='multi_eval')",context),false,"Evaluations must be isolated by course");
vm.runInContext("switchCourseByKey('EP-NIGHT-27',{render:false})",context);
assert.equal(vm.runInContext("getEvaluations().some(x=>x.id==='multi_eval')",context),true,"Course data must return when switching back");
vm.runInContext("switchCourseByKey('AEP-26',{render:false,force:true});go('settings')",context);assert.match(elements.get("#content").innerHTML,/Course Settings/);
assert.doesNotMatch(elements.get("#content").innerHTML,/ACTIVE PACKAGE/,"Course Settings must not repeat the large Active Package overview");
assert.match(elements.get("#content").innerHTML,/Create a course/);
assert.match(elements.get("#content").innerHTML,/Sector/);
assert.match(elements.get("#content").innerHTML,/Tailor active course/);
vm.runInContext("Object.assign(state,{settingsTab:'builder',builderType:'EP',builderProgram:'',builderCountry:'israel',builderStartsOn:'2026-09-30',builderName:'',builderNameManual:false,builderCode:'',builderCodeManual:false});render()",context);
assert.match(elements.get("#content").innerHTML,/Training Package/);
assert.match(elements.get("#content").innerHTML,/Course details/);
assert.match(elements.get("#content").innerHTML,/id="builderCountry"/);
assert.match(elements.get("#content").innerHTML,/id="builderStartsOn"/);
assert.doesNotMatch(elements.get("#content").innerHTML,/wizardMore/,"Course details must stay expanded");
assert.match(elements.get("#content").innerHTML,/data-builder-program="ep_rc_new"/);
assert.doesNotMatch(elements.get("#content").innerHTML,/data-builder-program="ep_full_new_mixed"/,"Create course must not offer a combined Day + Night EP Package");
assert.match(elements.get("#content").innerHTML,/data-builder-program="ep_full_day_new"/);
assert.match(elements.get("#content").innerHTML,/data-builder-program="ep_full_night_new"/);
assert.match(elements.get("#content").innerHTML,/data-builder-program="ep_full_atol"/);
assert.match(elements.get("#content").innerHTML,/data-builder-add-package="EP"/);
assert.doesNotMatch(elements.get("#content").innerHTML,/courseListCard|Open an existing course or continue tailoring its Package/,"Create course must not repeat the saved Courses list");
assert.doesNotMatch(elements.get("#content").innerHTML,/data-builder-platform=/);
assert.doesNotMatch(elements.get("#content").innerHTML,/data-builder-training=/);
assert.doesNotMatch(elements.get("#content").innerHTML,/Source library/);
vm.runInContext("Object.assign(state,{builderType:'IP',builderProgram:''});render()",context);
assert.match(elements.get("#content").innerHTML,/data-builder-program="ip_full_new_gcs_d"/);
assert.match(elements.get("#content").innerHTML,/data-builder-program="ip_full_new_gcs_c"/);
assert.match(elements.get("#content").innerHTML,/GCS-D/);
vm.runInContext("Object.assign(state,{builderType:'TECHNICIAN',builderProgram:''});render()",context);
assert.match(elements.get("#content").innerHTML,/data-builder-program="tech_full_new"/);
assert.match(elements.get("#content").innerHTML,/data-builder-program="tech_full_new_engine_d_gcs_c"/);
assert.match(elements.get("#content").innerHTML,/Engine H \/ GCS-D/);
vm.runInContext("Object.assign(state,{builderType:'IP',builderProgram:'ip_full_new_gcs_d',builderCountry:'cyprus',builderStartsOn:'2027-01-10',builderName:'',builderNameManual:false,builderCode:'',builderCodeManual:false});render()",context);
assert.match(elements.get("#content").innerHTML,/SELECTED PACKAGE/);
assert.match(elements.get("#content").innerHTML,/After creating the course/);
assert.match(elements.get("#content").innerHTML,/Course identity/);
assert.match(elements.get("#content").innerHTML,/suggested automatically/);
assert.match(elements.get("#content").innerHTML,/Cyprus/);
assert.match(elements.get("#content").innerHTML,/Jan 2027/);
assert.doesNotMatch(elements.get("#content").innerHTML,/Course name required/);
assert.match(elements.get("#content").innerHTML,/id="builderName" name="name" required value="[^"]+"/);
assert.match(elements.get("#content").innerHTML,/id="builderCode" name="code" value="[^"]+"/);
assert.match(elements.get("#content").innerHTML,/id="courseBuilderSubmit" type="submit" >Create course<\/button>/);
assert.match(vm.runInContext("builderSuggestedName('IP','cyprus','ip_full_new_gcs_d','2027-01-10')",context),/Cyprus · Jan 2027/);
assert.equal(vm.runInContext("builderAutoCode('Test Course','EP','2027-01-10')",context),"T-27");
assert.equal(vm.runInContext("uniqueAutoCourseCode('Aerostar External Pilot Course','EP')",context),"AEP-26-2","Automatic course codes must avoid the built-in course collision");
vm.runInContext("state.builderCountry='cyprus';render()",context);
assert.equal(vm.runInContext("state.builderProgram",context),"ip_full_new_gcs_d","Country changes must not clear the selected Package");
vm.runInContext("state.settingsTab='overrides';render()",context);assert.match(elements.get("#content").innerHTML,/Tailor active course/);
vm.runInContext("state.screen='roster';state.rosterManage=true;state.rosterType='TRAINEE';state.personEditKey='TRAINEE:t1';render()",context);
assert.match(elements.get("#content").innerHTML,/Add person/);
assert.match(elements.get("#content").innerHTML,/Remove from course/);
vm.runInContext("updateCourseMembership('t1','TRAINEE',{removed:true});state.personEditKey=null;render()",context);
assert.equal(vm.runInContext("courseTrainees().some(x=>x.id==='t1')",context),false);
assert.match(elements.get("#content").innerHTML,/assignExistingForm/,"Removed people should be available to reassign");
vm.runInContext("updateCourseMembership('t1','TRAINEE',{removed:false});Object.assign(currentCourseMeta,{type:'EP',phase:'Full Scale',platformId:'aerostar',trainingKind:'New Training',dayNight:'Day',country:'Israel',programId:'ep_full_day_new'});state.screen='profile';state.selectedTrainee='t1';state.profileTab='activity';render()",context);
assert.match(elements.get("#content").innerHTML,/Experience requirements/);
assert.match(elements.get("#content").innerHTML,/Takeoffs/);
assert.match(elements.get("#content").innerHTML,/Full-stop landings/);
assert.match(elements.get("#content").innerHTML,/0 \/ 3/);
assert.match(elements.get("#content").innerHTML,/Add external \/ historical experience/);
vm.runInContext("saveActivityEvents([{id:'legacy_takeoff',traineeId:'t1',date:'2026-09-29',type:'TAKEOFF',quantity:1,source:'Legacy evaluation',note:'Preflight'}])",context);
assert.equal(vm.runInContext("activityTotalsFor('t1').ep_full_day_takeoffs",context),1,"Legacy Full Scale takeoffs must map into the typed Day counter");
vm.runInContext("saveActivityEvents([])",context);
vm.runInContext("state.screen='evaluation';state.editingEval=null;render()",context);
assert.match(elements.get("#content").innerHTML,/Experience performed during this flight/);
assert.match(elements.get("#content").innerHTML,/name="takeoffs"/);
assert.match(elements.get("#content").innerHTML,/name="landings"/);
assert.match(elements.get("#content").innerHTML,/Full-stop landings performed/);
assert.deepEqual(JSON.parse(vm.runInContext("JSON.stringify(evaluationGradingSettings())",context)),{min:1,max:5,benchmark:4});
vm.runInContext("FLYMPUS_TRAINING.saveGlobalOverrides('ep_full_day_new',{program:{gradingMin:2,gradingBenchmark:3.5,gradingMax:6}});render()",context);
assert.deepEqual(JSON.parse(vm.runInContext("JSON.stringify(evaluationGradingSettings())",context)),{min:2,max:6,benchmark:3.5});
assert.equal(vm.runInContext("evaluationGradeOptions().join(',')",context),"2,3,4,5,6");
assert.match(elements.get("#content").innerHTML,/Benchmark 3\.5 · Scale 2–6/);
vm.runInContext("FLYMPUS_TRAINING.saveGlobalOverrides('ep_full_day_new',{});render()",context);
vm.runInContext("state.screen='settings';state.settingsTab='overrides';render()",context);
assert.match(elements.get("#content").innerHTML,/Package settings for this course/);
assert.match(elements.get("#content").innerHTML,/name="course_package_name"/);
assert.match(elements.get("#content").innerHTML,/Course status/);
assert.match(elements.get("#content").innerHTML,/name="course_lifecycle"/);
assert.match(elements.get("#content").innerHTML,/name="course_phase"/);
assert.match(elements.get("#content").innerHTML,/name="course_platform"/);
assert.match(elements.get("#content").innerHTML,/name="course_training"/);
assert.match(elements.get("#content").innerHTML,/courseSyllabusTable/);
assert.match(elements.get("#content").innerHTML,/courseSyllabusDragHandle/);
assert.doesNotMatch(elements.get("#content").innerHTML,/name="order_full_preflight"[^>]*type="number"/,"Tailor order must use drag, not manual numeric entry");
assert.match(elements.get("#content").innerHTML,/name="syll_name_full_preflight"/);
assert.match(elements.get("#content").innerHTML,/name="counter_name_ep_full_day_takeoffs"/);
assert.match(elements.get("#content").innerHTML,/name="criterion_name_flight_path_control"/);
assert.match(elements.get("#content").innerHTML,/name="course_grade_min"/);
assert.match(elements.get("#content").innerHTML,/name="course_grade_benchmark"/);
assert.match(elements.get("#content").innerHTML,/name="course_grade_max"/);
assert.match(elements.get("#content").innerHTML,/Grading settings/);
assert.match(elements.get("#content").innerHTML,/packageEditorItem/);
assert.match(elements.get("#content").innerHTML,/data-course-add-open="criteria"/);
assert.match(elements.get("#content").innerHTML,/id="courseTailorEdit"/);
assert.match(elements.get("#content").innerHTML,/courseTailorEditFieldset" disabled/);
assert.doesNotMatch(elements.get("#content").innerHTML,/Save changes<\/button>/,"Tailor must not show Save changes before Edit is selected");
assert.doesNotMatch(elements.get("#content").innerHTML,/Done editing/,"Tailor must use one Save changes action only");
assert.doesNotMatch(elements.get("#content").innerHTML,/resetCourseOverrides|Revert to Package defaults/,"Tailor must not expose a bulk reset-to-defaults action");
assert.match(elements.get("#content").innerHTML,/id="tailorCourseSelect"/,"Tailor must allow selecting an assigned course");
vm.runInContext("state.courseTailorEditing=true;render()",context);
const editingTailorHtml=elements.get("#content").innerHTML;
assert.match(editingTailorHtml,/courseTailorEditing/);
assert.match(editingTailorHtml,/courseTailorEditFieldset" >/);
assert.match(editingTailorHtml,/>Save changes<\/button>/);
assert.doesNotMatch(editingTailorHtml,/courseTailorDone|Done editing/);
assert.doesNotMatch(editingTailorHtml,/resetCourseOverrides|Revert to Package defaults/,"Tailor edit mode must keep only Save changes as the primary action");
assert.match(editingTailorHtml,/data-rule-table="criteria"/);
assert.match(editingTailorHtml,/data-rule-table="emergencies"/);
assert.match(editingTailorHtml,/data-rule-table="counters"/,"Full Scale course has experience requirements and should render their table");
assert.match(editingTailorHtml,/data-rule-table="exams"/,"Full Scale course has exams and should render their table");
assert.doesNotMatch(editingTailorHtml,/data-rule-table="progression"/,"Zero progression gates must not render an empty table header");
assert.doesNotMatch(editingTailorHtml,/Syllabi \/ practical tasks \([^)]*active\)/,"Syllabi count must match the other category summaries");
vm.runInContext("state.courseTailorEditing=false;render()",context);
assert.match(elements.get("#content").innerHTML,/data-course-add="syllabi"/);
assert.match(elements.get("#content").innerHTML,/data-course-add="counters"/);
assert.match(elements.get("#content").innerHTML,/data-course-add="criteria"/);
assert.match(elements.get("#content").innerHTML,/data-course-add="exams"/);
assert.match(elements.get("#content").innerHTML,/data-course-add="progression"/);
assert.match(elements.get("#content").innerHTML,/data-course-add="emergencies"/);
vm.runInContext("FLYMPUS_TRAINING.saveOverrides(currentCourseMeta.courseCode||currentCourseId,{program:{gradingMin:2,gradingBenchmark:3.5,gradingMax:6},custom:{syllabi:[{id:'ui_course_syll',name:'Course Test Syllabus',order:999,minimum:1,mode:'INSTRUCTED',instructorRequired:true,track:'day'}],counters:[{id:'ui_course_counter',name:'Course Test Counter',minimum:2,unit:'count',track:'shared',kind:'CUSTOM'}],criteria:[{id:'ui_course_criterion',name:'Course Test Criterion',weight:10}],exams:[{id:'ui_course_exam',name:'Course Test Exam',pass:80}],emergencies:[{id:'ui_course_emergency',name:'Course Test Emergency',category:'General / Operational'}]},emergencyRequirementIds:['ui_course_emergency']});render()",context);
assert.match(elements.get("#content").innerHTML,/Course Test Syllabus/);
assert.match(elements.get("#content").innerHTML,/Course Test Counter/);
assert.match(elements.get("#content").innerHTML,/COURSE ONLY/);
vm.runInContext("state.courseTailorEditing=true;render()",context);
assert.doesNotMatch(elements.get("#content").innerHTML,/resetCourseOverrides|Revert to Package defaults/);
vm.runInContext("state.courseTailorEditing=false;state.screen='evaluation';render()",context);
assert.match(elements.get("#content").innerHTML,/Course Test Syllabus/,"Course-only syllabus must flow into Evaluation");
assert.match(elements.get("#content").innerHTML,/Course Test Criterion/,"Course-only criterion must flow into Evaluation");
assert.match(elements.get("#content").innerHTML,/Course Test Emergency/,"Course-only emergency must flow into Evaluation");
assert.match(elements.get("#content").innerHTML,/Benchmark 3\.5 · Scale 2–6/,"Tailor grading override must flow into Evaluation");
vm.runInContext("FLYMPUS_TRAINING.saveOverrides(currentCourseMeta.courseCode||currentCourseId,{});state.screen='settings';state.settingsTab='catalog';state.typeWorkspace='EP';state.packageFocusId=null;state.packageEditId=null;render()",context);
const advancedHtml=elements.get("#content").innerHTML;
assert.match(advancedHtml,/Advanced/);
assert.doesNotMatch(advancedHtml,/data-settings-tab="packages"/,"Packages must not have a separate Settings tab");
assert.match(advancedHtml,/Define sectors/);
assert.match(advancedHtml,/Select sector to edit/);
assert.match(advancedHtml,/>Architecture<\/b>/);
assert.doesNotMatch(advancedHtml,/Phases · EP|Platforms · EP|EP architecture/,'Selected sector must not be repeated in Advanced headings');
assert.match(advancedHtml,/class="toolbar packageSaveBar advancedArchitectureActions"/,"Advanced Edit must use the same sticky action bar behavior as Tailor");
assert.match(advancedHtml,/id="advancedArchitectureEdit">Edit<\/button>/);
assert.doesNotMatch(advancedHtml,/advancedEditBar/,"Advanced must not use a separate top Edit panel");
assert.match(advancedHtml,/advancedEditFieldset" disabled/,"Advanced architecture must be view-only until Edit is pressed");
assert.doesNotMatch(advancedHtml,/Save architecture/);
assert.doesNotMatch(advancedHtml,/Reset architecture labels/);
assert.match(advancedHtml,/Final step · create and manage reusable Packages/);
assert.match(advancedHtml,/data-cfg-add-open="courseTypes"/);
assert.match(advancedHtml,/class="toolbar cfgAddForm cfgAddPanel" data-kind="courseTypes" hidden/);
assert.match(advancedHtml,/data-cfg-add-cancel="courseTypes"/);
assert.doesNotMatch(advancedHtml,/>Add course types<\/input>/);
assert.match(advancedHtml,/Packages/);
assert.match(advancedHtml,/Choose Edit to create, change or delete Packages/);
assert.doesNotMatch(advancedHtml,/Open Packages/);
assert.doesNotMatch(advancedHtml,/data-open-packages-page=/);
assert.doesNotMatch(advancedHtml,/data-package-assign-open="EP"/,"Create Package must stay hidden before Advanced Edit");
assert.doesNotMatch(advancedHtml,/data-package-assign-panel="EP"/,"Package creation form must not exist before Advanced Edit");
vm.runInContext("state.advancedArchitectureEditing=true;render()",context);
const advancedEditingHtml=elements.get("#content").innerHTML;
assert.match(advancedEditingHtml,/class="toolbar packageSaveBar advancedArchitectureActions"/);
assert.match(advancedEditingHtml,/id="cfgSaveCatalogs">Save changes<\/button>/);
assert.match(advancedEditingHtml,/Edit architecture/);
assert.doesNotMatch(advancedEditingHtml,/advancedEditFieldset" disabled/,"Edit must unlock Advanced architecture controls");
assert.match(advancedEditingHtml,/id="typeWorkspace" disabled/,"Sector selection stays fixed while editing");
assert.match(advancedEditingHtml,/data-package-assign-open="EP"/,"Create Package appears only after Advanced Edit");
assert.match(advancedEditingHtml,/data-package-assign-panel="EP" hidden/);
assert.match(advancedEditingHtml,/globalPackageForm[\s\S]*?<fieldset class="packageEditFieldset" >/,"Advanced Edit must also unlock Packages");
assert.doesNotMatch(advancedEditingHtml,/Save Package|Save & Done|Done editing/,"Configuration editing must use one Save changes action");
vm.runInContext("state.advancedArchitectureEditing=true;state.packageCreateOpen='EP';render()",context);
const advancedCreateOpenHtml=elements.get("#content").innerHTML;
assert.match(advancedCreateOpenHtml,/data-package-assign-open="EP" hidden/);
assert.match(advancedCreateOpenHtml,/data-package-assign-panel="EP" >/);
assert.match(advancedCreateOpenHtml,/id="sectorPackageForm"/);
assert.match(advancedCreateOpenHtml,/Create & edit Package/);
vm.runInContext("state.packageCreateOpen=null;state.advancedArchitectureEditing=false;render()",context);
assert.match(advancedCreateOpenHtml,/value="EP ·/,"A suggested Package name should be prefilled when Package creation is opened");
assert.match(advancedHtml,/Qualifications/);
assert.match(advancedHtml,/Shahak/,"Platform rename must be visible from the source architecture");
assert.doesNotMatch(advancedHtml,/class="pill gray">rc_model<\/span>/,"Internal platform IDs must not be displayed beside platform names");
assert.match(advancedHtml,/data-kind="qualifications"/);
assert.match(advancedHtml,/value="Day"/);
assert.match(advancedHtml,/value="Night"/);
assert.match(advancedHtml,/value="ATOL"/);
assert.doesNotMatch(advancedHtml,/Package configuration · Operating track|Mixed \/ Day\+Night/,"EP architecture must use Qualifications instead of the old track context");
assert.match(advancedHtml,/id="cfgAddPlatform"/);
assert.match(advancedHtml,/globalPackageForm/,"Advanced must contain the full Package editor");
assert.match(advancedHtml,/EP ATOL Qualification · Full Scale · Aerostar/,"ATOL must be a standalone EP Full Scale Package, not a Day\/Night track");
assert.match(advancedHtml,/Qualification/,"EP Package paths must expose Qualification as the relevant dimension");
assert.match(advancedHtml,/data-global-add="syllabi"/);
assert(advancedHtml.indexOf("Course types")<advancedHtml.indexOf("Select sector to edit"),"Course types must render before sector selection");
assert(advancedHtml.indexOf("Select sector to edit")<advancedHtml.indexOf(">Architecture</b>"),"Architecture follows sector selection");
assert(advancedHtml.indexOf(">Architecture</b>")<advancedHtml.indexOf("Final step · create and manage reusable Packages"),"Packages must be the final Advanced step");

vm.runInContext("const cp=getCustomPlatforms();cp.EP=[{id:'platform_test',name:'Test Platform'}];saveCustomPlatforms(cp);const labels=getPlatformLabels();labels.platform_test='Test Platform';savePlatformLabels(labels);render()",context);
assert.match(elements.get("#content").innerHTML,/Test Platform/);
assert.match(elements.get("#content").innerHTML,/data-platform-remove="platform_test"/);
assert.match(elements.get("#content").innerHTML,/value="platform_test"/);

vm.runInContext("FLYMPUS_TRAINING.saveCustomPackage('EP',{id:'ui_custom_package',name:'EP · UI Custom Package',phaseId:'ep_full',platformId:'aerostar',trainingKind:'new',dayNight:'day',gradingMin:1,gradingBenchmark:4,gradingMax:5,theory:[],syllabi:[],criteria:[],experienceCounters:[],exams:[],progression:[],emergencyRequirementIds:[],courseEmergencies:[]});state.packageFocusId=null;render()",context);
const collapsedPackagesHtml=elements.get("#content").innerHTML;
assert.match(collapsedPackagesHtml,/EP · UI Custom Package/);
assert.match(collapsedPackagesHtml,/packageEditorShell/);
assert.doesNotMatch(collapsedPackagesHtml,/packageEditorShell" open/,"Advanced Package list must start collapsed");
assert.doesNotMatch(collapsedPackagesHtml,/packageRules syllabiRules" open/,"Syllabi must start collapsed");

vm.runInContext("state.packageFocusId='ui_custom_package';render()",context);
const packagesHtml=elements.get("#content").innerHTML;
assert.match(packagesHtml,/Training Packages/);
assert.match(packagesHtml,/id="packageCategoryFilter"/,"Training Packages must provide a category filter when multiple categories exist");
assert.match(packagesHtml,/Refreshment/);
assert.match(packagesHtml,/Qualification/);
assert.match(packagesHtml,/Return to Currency/);
assert.doesNotMatch(packagesHtml,/EP Training Packages|IP Training Packages|TECHNICIAN Training Packages/,'Training Packages heading must not repeat the selected sector');
assert.match(packagesHtml,/globalPackageForm/);
assert.match(packagesHtml,/Syllabi \/ practical tasks/);
assert.match(packagesHtml,/packageSyllabusTable/);
assert.match(packagesHtml,/Order \/ Move/);
assert.match(packagesHtml,/Series \/ Syllabus/);
assert.match(packagesHtml,/Instructor Presence/);
assert.match(packagesHtml,/syllabusDragHandle/);
assert.doesNotMatch(packagesHtml,/name="g_syll_order_[^"]+" type="number"/,"Order must not be manually editable");
assert.match(packagesHtml,/type="hidden" name="g_syll_order_/);
assert.doesNotMatch(packagesHtml,/data-package-edit-toggle=/,"Package editing is controlled by the global Advanced Edit action");
assert.doesNotMatch(packagesHtml,/data-delete-package="ui_custom_package"/,"Delete Package must stay hidden until Advanced Edit is active");
vm.runInContext("state.packageCategoryFilter='refreshment';state.packageFocusId=null;render()",context);
const refreshmentFilteredHtml=elements.get("#content").innerHTML;
assert.match(refreshmentFilteredHtml,/1 of \d+ packages/);
assert.match(refreshmentFilteredHtml,/EP Refreshment · Full Scale · Aerostar/);
assert.doesNotMatch(refreshmentFilteredHtml,/EP Return to Currency · Full Scale · Aerostar/);
assert.doesNotMatch(refreshmentFilteredHtml,/EP ATOL Qualification · Full Scale · Aerostar/);
vm.runInContext("state.packageCategoryFilter='ALL';state.packageFocusId='ui_custom_package';render()",context);
assert.match(packagesHtml,/total planned minimum/);
assert.doesNotMatch(packagesHtml,/packageRules syllabiRules"[^>]* open/,"Focused Package may open, but Syllabi must remain collapsed until requested");
vm.runInContext("state.packageAddFlow='ui_custom_package:syllabi';render()",context);
const continuousSyllabusHtml=elements.get("#content").innerHTML;
assert.match(continuousSyllabusHtml,/packageRules syllabiRules" data-package-rule="syllabi" data-package-id="ui_custom_package" open/);
assert.match(continuousSyllabusHtml,/data-global-add-open="syllabi" hidden/);
assert.match(continuousSyllabusHtml,/data-global-add-panel="syllabi" >/);
assert.match(continuousSyllabusHtml,/Done adding/);
assert.match(continuousSyllabusHtml,/row stays open for the next syllabus/);
vm.runInContext("state.packageAddFlow=null;render()",context);
assert.match(packagesHtml,/Assessment criteria/);
assert.match(packagesHtml,/Grading settings/);
assert.match(packagesHtml,/name="g_grade_min"/);
assert.match(packagesHtml,/name="g_grade_benchmark"/);
assert.match(packagesHtml,/name="g_grade_max"/);
assert.match(packagesHtml,/Emergency requirements/);
assert.match(packagesHtml,/data-global-add-open="syllabi"/);
assert.match(packagesHtml,/data-global-add-panel="syllabi" hidden/);
assert.match(packagesHtml,/data-global-add-cancel="syllabi"/);
assert.match(packagesHtml,/data-global-add="criteria"/);
assert.match(packagesHtml,/data-global-add="emergencies"/);
assert.match(packagesHtml,/data-global-add="counters"/);
assert.match(packagesHtml,/data-global-add="exams"/);
assert.match(packagesHtml,/data-global-add="progression"/);
assert.match(packagesHtml,/packageFocused/);
assert.doesNotMatch(packagesHtml,/EDITED DEFAULT/);
assert.doesNotMatch(packagesHtml,/>DEFAULT<\/span>/);
assert.doesNotMatch(packagesHtml,/>EP<\/span>/);
assert.doesNotMatch(packagesHtml,/packageEditing/,"Focused Package is view mode until Edit is selected");

vm.runInContext("state.advancedArchitectureEditing=true;render()",context);
const editingPackageHtml=elements.get("#content").innerHTML;
assert.match(editingPackageHtml,/packageEditing/);
assert.doesNotMatch(editingPackageHtml,/Done editing|Save Package|Save & Done/,"Advanced must use the single sticky Save changes action");
assert.match(editingPackageHtml,/Delete Package/);
assert.doesNotMatch(editingPackageHtml,/Restore original Package defaults|data-reset-global-package/,"Package edit mode must not expose a destructive bulk restore-to-defaults action");
assert.match(editingPackageHtml,/data-delete-package="ui_custom_package"/,"Delete Package must appear while Advanced Edit is active");
assert.match(editingPackageHtml,/data-global-package-id="ui_custom_package"[\s\S]*?<fieldset class="packageEditFieldset" >/,"Advanced Edit must unlock Package editors");
const customPackageStart=editingPackageHtml.indexOf('data-global-package-id="ui_custom_package"');
const customPackageEnd=editingPackageHtml.indexOf('</form>',customPackageStart);
const customEditingPackageHtml=editingPackageHtml.slice(customPackageStart,customPackageEnd>customPackageStart?customPackageEnd:editingPackageHtml.length);
assert.doesNotMatch(customEditingPackageHtml,/data-rule-table="criteria"/,"Empty criteria must not render a header-only table");
assert.match(customEditingPackageHtml,/data-rule-table="emergencies"/,"Platform emergency choices remain visible even when none are required");
assert.doesNotMatch(customEditingPackageHtml,/data-rule-table="counters"/,"Empty experience requirements must not render a header-only table");
assert.doesNotMatch(customEditingPackageHtml,/data-rule-table="exams"/,"Empty exams must not render a header-only table");
assert.doesNotMatch(customEditingPackageHtml,/data-rule-table="progression"/,"Empty progression gates must not render a header-only table");

vm.runInContext("FLYMPUS_TRAINING.saveGlobalOverrides('ep_full_day_new',{syllabi:{full_intro:{applicable:false}}});state.packageFocusId='ep_full_day_new';state.advancedArchitectureEditing=true;render()",context);
const excludedSyllabusHtml=elements.get("#content").innerHTML;
assert.match(excludedSyllabusHtml,/Excluded syllabi \(<span data-excluded-syllabus-count>1<\/span>\)/);
assert.match(excludedSyllabusHtml,/data-restore-syllabus="full_intro"/);
assert.match(excludedSyllabusHtml,/data-syllabus-row="full_intro"[\s\S]*?syllabusExcludedRow|syllabusExcludedRow[\s\S]*?data-syllabus-row="full_intro"/);
assert.match(excludedSyllabusHtml,/data-syllabus-row="full_positions_a"[\s\S]*?<span class="syllabusOrderNumber">2<\/span>/,"Active syllabus order must close the gap when Introduction is excluded");
assert.match(excludedSyllabusHtml,/Only included syllabi are numbered/);

vm.runInContext("FLYMPUS_TRAINING.saveGlobalOverrides('ep_full_day_new',{});state.packageFocusId='ui_custom_package';state.advancedArchitectureEditing=true;render()",context);
vm.runInContext("FLYMPUS_TRAINING.saveGlobalOverrides('ep_full_refresh',{custom:{syllabi:[{id:'ui_pkg_syll',name:'Reusable Package Syllabus',order:99,minimum:1,mode:'INSTRUCTED',instructorRequired:true,track:'day'}],criteria:[{id:'ui_pkg_criterion',name:'Reusable Package Criterion',weight:10}],emergencies:[{id:'ui_pkg_emergency',name:'Reusable Package Emergency',category:'General / Operational'}]},emergencyRequirementIds:['ui_pkg_emergency']});render()",context);
assert.match(elements.get("#content").innerHTML,/Reusable Package Syllabus/);
assert.match(elements.get("#content").innerHTML,/Reusable Package Criterion/);
assert.match(elements.get("#content").innerHTML,/Reusable Package Emergency/);
assert.match(elements.get("#content").innerHTML,/PACKAGE CUSTOM/);

vm.runInContext("FLYMPUS_TRAINING.saveGlobalOverrides('ep_full_refresh',{});FLYMPUS_TRAINING.removeCustomPackage('EP','ui_custom_package');state.settingsTab='catalog';state.typeWorkspace='IP';state.packageFocusId=null;state.packageEditId=null;render()",context);
assert.match(elements.get("#content").innerHTML,/Configurations \/ qualifications/);
assert.match(elements.get("#content").innerHTML,/Training Packages/);
assert.doesNotMatch(elements.get("#content").innerHTML,/IP Training Packages/);
assert.doesNotMatch(elements.get("#content").innerHTML,/Phases · IP|Platforms · IP|IP architecture/);
assert.match(elements.get("#content").innerHTML,/globalPackageForm/);

vm.runInContext("state.typeWorkspace='TECHNICIAN';state.packageFocusId=null;state.packageEditId=null;render()",context);
assert.match(elements.get("#content").innerHTML,/Systems \/ qualifications/);
assert.match(elements.get("#content").innerHTML,/Engine H \/ GCS-D/);
assert.match(elements.get("#content").innerHTML,/Training Packages/);
assert.doesNotMatch(elements.get("#content").innerHTML,/TECHNICIAN Training Packages/);
assert.doesNotMatch(elements.get("#content").innerHTML,/Phases · TECHNICIAN|Platforms · TECHNICIAN|TECHNICIAN architecture/);
vm.runInContext("FLYMPUS_TRAINING.saveGlobalOverrides('tech_full_new',{program:{name:'Global Technician Package'}});render()",context);
assert.match(elements.get("#content").innerHTML,/Global Technician Package/);
assert.doesNotMatch(elements.get("#content").innerHTML,/EDITED DEFAULT/,"Package state badges were intentionally removed");
vm.runInContext("FLYMPUS_TRAINING.saveGlobalOverrides('tech_full_new',{})",context);
vm.runInContext("Object.assign(currentCourseMeta,{type:'TECHNICIAN',phase:'Full Scale',platformId:'aerostar',trainingKind:'New Training',dayNight:'Mixed \/ Day+Night',country:'Israel',programId:'tech_full_new'});state.screen='profile';state.profileTab='activity';render()",context);
assert.match(elements.get("#content").innerHTML,/Practical experience/);
assert.match(elements.get("#content").innerHTML,/Record practical task/);
assert.match(elements.get("#content").innerHTML,/Engine Installation \/ Removal/);
assert.match(elements.get("#content").innerHTML,/name="quantity" type="number" min="1" step="1"/);
console.log(JSON.stringify({ok:true,myCourses:true,multiCourse:true,courseIsolation:true,instructorAssignments:true,home:true,settings:true,directPackageCourseCreation:true,inlineCourseDetails:true,suggestedCourseIdentity:true,builderAddPackageShortcut:true,createCourseValidation:true,uniqueCourseCode:true,trainingPackages:true,packagesInsideAdvanced:true,advancedPackagesLast:true,sectorPackageAssignment:true,suggestedPackageName:true,fullPackageEditor:true,packageGradingSettings:true,alignedTailorEditor:true,tailorExplicitEditMode:true,tailorGradingOverride:true,tailorDragSyllabus:true,dynamicEvaluationGradeScale:true,collapsedPackageEditor:true,compactSyllabusTable:true,dragSyllabusOrdering:true,smoothDragAnimation:true,compactAddRows:true,continuousSyllabusEntry:true,compactCatalogAdd:true,activeOrderReindex:true,excludedSyllabusRestore:true,packageEditMode:true,packageDelete:true,editOnlyPackageDelete:true,globalPackageCustomItems:true,globalPackagePath:true,globalPackageDefaults:true,coursePackageOverride:true,courseOnlyItems:true,professionContext:true,advancedOrder:true,customPlatforms:true,overrides:true,rosterMembership:true,experienceUx:true,technicianExperience:true}));
