const fs=require("node:fs");
const vm=require("node:vm");
const assert=require("node:assert/strict");
const storage=()=>{const values=new Map();return{getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key)}};
class ElementStub{
  constructor(){this.innerHTML="";this.textContent="";this.value="";this.dataset={};this.style={};this.classList={add(){},remove(){},toggle(){}}}
  querySelectorAll(){return[]} querySelector(){return null} addEventListener(){} click(){} appendChild(){}
}
const elements=new Map(["#menuBtn","#backdrop","#nav","#content","#drawer","#toast"].map(id=>[id,new ElementStub()]));
const document={querySelector:selector=>elements.get(selector)||null,querySelectorAll:()=>[],createElement:()=>new ElementStub()};
const context={window:{},document,localStorage:storage(),sessionStorage:storage(),console,confirm:()=>true,setTimeout:()=>0,clearTimeout(){},Date,Math,JSON,Number,String,Array,Object,Map,Set,FormData:class{},Blob:class{},URL:{createObjectURL(){return""},revokeObjectURL(){}},location:{},navigator:{}};
context.window=context;vm.createContext(context);
for(const file of ["assets/ep-catalog.js","assets/aerostar-platform.js","assets/ip-catalog.js","assets/technician-catalog.js","assets/training-core.js","assets/ep-lessons-screening.js","assets/ep-lessons-rc-1.js","assets/ep-lessons-rc-2.js","assets/ep-lessons-half.js","assets/ep-lessons-full-day-a.js","assets/ep-lessons-full-day-b.js","assets/ep-lessons-night.js"]){vm.runInContext(fs.readFileSync(file,"utf8"),context,{filename:file})}
const html=fs.readFileSync("index.html","utf8");
const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(match=>match[1]).filter(x=>x.trim());
assert.equal(scripts.length,1);vm.runInContext(scripts[0],context,{filename:"index-inline.js"});
assert.match(elements.get("#content").innerHTML,/My Courses/);
assert.match(elements.get("#content").innerHTML,/Aerostar EP Course/);
assert.equal(vm.runInContext("instructorAssignedCourses(currentUserId).length",context),1);
vm.runInContext("go('home')",context);assert(elements.get("#content").innerHTML.length>1000,"Home must render");
vm.runInContext(`localStorage.setItem('ct-review-courses',JSON.stringify([{id:'course_multi',name:'Aerostar EP Night 2027',code:'EP-NIGHT-27',summary:'EP · Full Scale · Aerostar · Night',startsOn:'2027-01-10',selection:{courseType:'EP',phaseId:'ep_full',platformId:'aerostar',trainingKind:'new',dayNight:'night',country:'israel'},platformId:'aerostar',programId:'ep_full_night_new'}]));updateCourseMembershipForCourse('EP-NIGHT-27',currentUserId,'INSTRUCTOR',{role:'COURSE_MANAGER',removed:false});state.screen='courses';render()`,context);
assert.match(elements.get("#content").innerHTML,/Aerostar EP Night 2027/);
assert.equal(vm.runInContext("instructorAssignedCourses(currentUserId).length",context),2);
assert.equal(vm.runInContext("instructorAssignedCourses('i2').some(x=>courseKey(x)==='EP-NIGHT-27')",context),false);
vm.runInContext("updateCourseMembershipForCourse('EP-NIGHT-27','i2','INSTRUCTOR',{role:'INSTRUCTOR',removed:false})",context);
assert.equal(vm.runInContext("instructorAssignedCourses('i2').some(x=>courseKey(x)==='EP-NIGHT-27')",context),true);
vm.runInContext("switchCourseByKey('EP-NIGHT-27',{render:false});setEvaluations([{id:'multi_eval',flightDate:'2027-01-11',traineeId:'t1',instructorId:'i1',syllabus:'Takeoff',grade:4}])",context);
assert.equal(vm.runInContext("getEvaluations().length",context),1);
vm.runInContext("switchCourseByKey('AEP-26',{render:false,force:true})",context);
assert.equal(vm.runInContext("getEvaluations().some(x=>x.id==='multi_eval')",context),false,"Evaluations must be isolated by course");
vm.runInContext("switchCourseByKey('EP-NIGHT-27',{render:false})",context);
assert.equal(vm.runInContext("getEvaluations().some(x=>x.id==='multi_eval')",context),true,"Course data must return when switching back");
vm.runInContext("switchCourseByKey('AEP-26',{render:false,force:true});go('settings')",context);assert.match(elements.get("#content").innerHTML,/Course Settings/);
assert.match(elements.get("#content").innerHTML,/Create a course/);
assert.match(elements.get("#content").innerHTML,/Sector/);
assert.match(elements.get("#content").innerHTML,/Tailor active course/);
vm.runInContext("Object.assign(state,{settingsTab:'builder',builderType:'EP',builderProgram:'',builderCountry:'israel'});render()",context);
assert.match(elements.get("#content").innerHTML,/Training Package/);
assert.match(elements.get("#content").innerHTML,/data-builder-program="ep_rc_new"/);
assert.match(elements.get("#content").innerHTML,/data-builder-program="ep_full_new_mixed"/);
assert.doesNotMatch(elements.get("#content").innerHTML,/data-builder-platform=/);
assert.doesNotMatch(elements.get("#content").innerHTML,/data-builder-training=/);
assert.doesNotMatch(elements.get("#content").innerHTML,/Source library/);
vm.runInContext("Object.assign(state,{builderType:'IP',builderProgram:''});render()",context);
assert.match(elements.get("#content").innerHTML,/data-builder-program="ip_full_new_gcs_d"/);
assert.match(elements.get("#content").innerHTML,/data-builder-program="ip_full_new_gcs_c"/);
assert.match(elements.get("#content").innerHTML,/GCS-D/);
vm.runInContext("Object.assign(state,{builderType:'TECHNICIAN',builderProgram:''});render()",context);
assert.match(elements.get("#content").innerHTML,/data-builder-program="tech_full_new"/);
assert.match(elements.get("#content").innerHTML,/data-builder-program="tech_full_new_engine_d_gcs_c"/);
assert.match(elements.get("#content").innerHTML,/Engine H \/ GCS-D/);
vm.runInContext("Object.assign(state,{builderType:'IP',builderProgram:'ip_full_new_gcs_d',builderName:''});render()",context);
assert.match(elements.get("#content").innerHTML,/SELECTED PACKAGE/);
assert.match(elements.get("#content").innerHTML,/After creating the course/);
assert.match(elements.get("#content").innerHTML,/Course name required/);
assert.match(elements.get("#content").innerHTML,/id="courseBuilderSubmit" type="submit" >Create course<\/button>/,"Selected Package should keep Create clickable so missing name gets explicit feedback");
assert.equal(vm.runInContext("uniqueAutoCourseCode('Aerostar External Pilot Course','EP')",context),"AEP-26-2","Automatic course codes must avoid the built-in course collision");
vm.runInContext("state.builderCountry='cyprus';render()",context);
assert.equal(vm.runInContext("state.builderProgram",context),"ip_full_new_gcs_d","Country changes must not clear the selected Package");
vm.runInContext("state.settingsTab='overrides';render()",context);assert.match(elements.get("#content").innerHTML,/Tailor active course/);
vm.runInContext("state.screen='roster';state.rosterManage=true;state.rosterType='TRAINEE';state.personEditKey='TRAINEE:t1';render()",context);
assert.match(elements.get("#content").innerHTML,/Add person/);
assert.match(elements.get("#content").innerHTML,/Remove from course/);
vm.runInContext("updateCourseMembership('t1','TRAINEE',{removed:true});state.personEditKey=null;render()",context);
assert.equal(vm.runInContext("courseTrainees().some(x=>x.id==='t1')",context),false);
assert.match(elements.get("#content").innerHTML,/assignExistingForm/,"Removed people should be available to reassign");
vm.runInContext("updateCourseMembership('t1','TRAINEE',{removed:false});Object.assign(currentCourseMeta,{type:'EP',phase:'Full Scale',platformId:'aerostar',trainingKind:'New Training',dayNight:'Day',country:'Israel',programId:'ep_full_day_new'});state.screen='profile';state.selectedTrainee='t1';state.profileTab='activity';render()",context);
assert.match(elements.get("#content").innerHTML,/Experience requirements/);
assert.match(elements.get("#content").innerHTML,/Takeoffs/);
assert.match(elements.get("#content").innerHTML,/Full-stop landings/);
assert.match(elements.get("#content").innerHTML,/0 \/ 3/);
assert.match(elements.get("#content").innerHTML,/Add external \/ historical experience/);
vm.runInContext("saveActivityEvents([{id:'legacy_takeoff',traineeId:'t1',date:'2026-09-29',type:'TAKEOFF',quantity:1,source:'Legacy evaluation',note:'Preflight'}])",context);
assert.equal(vm.runInContext("activityTotalsFor('t1').ep_full_day_takeoffs",context),1,"Legacy Full Scale takeoffs must map into the typed Day counter");
vm.runInContext("saveActivityEvents([])",context);
vm.runInContext("state.screen='evaluation';state.editingEval=null;render()",context);
assert.match(elements.get("#content").innerHTML,/Experience performed during this flight/);
assert.match(elements.get("#content").innerHTML,/name="takeoffs"/);
assert.match(elements.get("#content").innerHTML,/name="landings"/);
assert.match(elements.get("#content").innerHTML,/Full-stop landings performed/);
vm.runInContext("state.screen='settings';state.settingsTab='overrides';render()",context);
assert.match(elements.get("#content").innerHTML,/Package settings for this course/);
assert.match(elements.get("#content").innerHTML,/name="course_package_name"/);
assert.match(elements.get("#content").innerHTML,/name="course_phase"/);
assert.match(elements.get("#content").innerHTML,/name="course_platform"/);
assert.match(elements.get("#content").innerHTML,/name="course_training"/);
assert.match(elements.get("#content").innerHTML,/name="syll_name_full_preflight"/);
assert.match(elements.get("#content").innerHTML,/name="counter_name_ep_full_day_takeoffs"/);
assert.match(elements.get("#content").innerHTML,/name="criterion_name_flight_path_control"/);
assert.match(elements.get("#content").innerHTML,/data-course-add="syllabi"/);
assert.match(elements.get("#content").innerHTML,/data-course-add="counters"/);
assert.match(elements.get("#content").innerHTML,/data-course-add="criteria"/);
assert.match(elements.get("#content").innerHTML,/data-course-add="exams"/);
assert.match(elements.get("#content").innerHTML,/data-course-add="progression"/);
assert.match(elements.get("#content").innerHTML,/data-course-add="emergencies"/);
vm.runInContext("FLYMPUS_TRAINING.saveOverrides(currentCourseMeta.courseCode||currentCourseId,{custom:{syllabi:[{id:'ui_course_syll',name:'Course Test Syllabus',order:999,minimum:1,mode:'INSTRUCTED',instructorRequired:true,track:'day'}],counters:[{id:'ui_course_counter',name:'Course Test Counter',minimum:2,unit:'count',track:'shared',kind:'CUSTOM'}],criteria:[{id:'ui_course_criterion',name:'Course Test Criterion',weight:10}],exams:[{id:'ui_course_exam',name:'Course Test Exam',pass:80}],emergencies:[{id:'ui_course_emergency',name:'Course Test Emergency',category:'General / Operational'}]},emergencyRequirementIds:['ui_course_emergency']});render()",context);
assert.match(elements.get("#content").innerHTML,/Course Test Syllabus/);
assert.match(elements.get("#content").innerHTML,/Course Test Counter/);
assert.match(elements.get("#content").innerHTML,/COURSE ONLY/);
vm.runInContext("state.screen='evaluation';render()",context);
assert.match(elements.get("#content").innerHTML,/Course Test Syllabus/,"Course-only syllabus must flow into Evaluation");
assert.match(elements.get("#content").innerHTML,/Course Test Criterion/,"Course-only criterion must flow into Evaluation");
assert.match(elements.get("#content").innerHTML,/Course Test Emergency/,"Course-only emergency must flow into Evaluation");
vm.runInContext("FLYMPUS_TRAINING.saveOverrides(currentCourseMeta.courseCode||currentCourseId,{});state.screen='settings';state.settingsTab='catalog';state.typeWorkspace='EP';render()",context);
const advancedHtml=elements.get("#content").innerHTML;
assert.match(advancedHtml,/Advanced/);
assert.match(advancedHtml,/Define sectors/);
assert.match(advancedHtml,/Select sector to edit/);
assert.match(advancedHtml,/Packages assigned to EP/);
assert.match(advancedHtml,/id="sectorPackageForm"/);
assert.match(advancedHtml,/Create & edit Package/);
assert.match(advancedHtml,/value="EP ·/,"A suggested Package name should be prefilled after selecting a sector");
assert.match(advancedHtml,/Training tracks · Day \/ Night/);
assert.match(advancedHtml,/id="cfgAddPlatform"/);
assert.doesNotMatch(advancedHtml,/globalPackageForm/,"Advanced must not render the Package editor");
assert.doesNotMatch(advancedHtml,/data-global-add="syllabi"/,"Package content editing belongs on the Packages page");
assert(advancedHtml.indexOf("Course types")<advancedHtml.indexOf("Select sector to edit"),"Course types must render before sector selection");
assert(advancedHtml.indexOf("Select sector to edit")<advancedHtml.indexOf("Packages assigned to EP"),"Package assignment must follow sector selection");
vm.runInContext("const cp=getCustomPlatforms();cp.EP=[{id:'platform_test',name:'Test Platform'}];saveCustomPlatforms(cp);const labels=getPlatformLabels();labels.platform_test='Test Platform';savePlatformLabels(labels);render()",context);
assert.match(elements.get("#content").innerHTML,/Test Platform/);
assert.match(elements.get("#content").innerHTML,/data-platform-remove="platform_test"/);
assert.match(elements.get("#content").innerHTML,/value="platform_test"/);
vm.runInContext("FLYMPUS_TRAINING.saveCustomPackage('EP',{id:'ui_custom_package',name:'EP · UI Custom Package',phaseId:'ep_full',platformId:'aerostar',trainingKind:'new',dayNight:'day',theory:[],syllabi:[],criteria:[],experienceCounters:[],exams:[],progression:[],emergencyRequirementIds:[],courseEmergencies:[]});render()",context);
assert.match(elements.get("#content").innerHTML,/EP · UI Custom Package/);
assert.match(elements.get("#content").innerHTML,/data-open-package="ui_custom_package"/);
vm.runInContext("state.settingsTab='packages';state.packageWorkspace='EP';state.packageFocusId=null;render()",context);
const collapsedPackagesHtml=elements.get("#content").innerHTML;
assert.match(collapsedPackagesHtml,/packageEditorShell/);
assert.doesNotMatch(collapsedPackagesHtml,/packageEditorShell" open/,"Packages page must start with every Package collapsed");
assert.doesNotMatch(collapsedPackagesHtml,/packageRules syllabiRules" open/,"Syllabi must start collapsed");
vm.runInContext("state.packageFocusId='ui_custom_package';render()",context);
const packagesHtml=elements.get("#content").innerHTML;
assert.match(packagesHtml,/REUSABLE TRAINING PACKAGES/);
assert.doesNotMatch(packagesHtml,/Build and edit reusable Packages here/);
assert.doesNotMatch(packagesHtml,/Packages start collapsed/);
assert.match(packagesHtml,/globalPackageForm/);
assert.match(packagesHtml,/Syllabi \/ practical tasks/);
assert.match(packagesHtml,/packageSyllabusTable/);
assert.match(packagesHtml,/Order \/ Move/);
assert.match(packagesHtml,/Series \/ Syllabus/);
assert.match(packagesHtml,/Instructor Presence/);
assert.match(packagesHtml,/syllabusDragHandle/);
assert.doesNotMatch(packagesHtml,/name="g_syll_order_[^"]+" type="number"/,"Order must not be manually editable");
assert.match(packagesHtml,/type="hidden" name="g_syll_order_/);
assert.match(packagesHtml,/data-package-edit-toggle="ui_custom_package"/);
assert.doesNotMatch(packagesHtml,/data-delete-package="ui_custom_package"/,"Delete Package must stay hidden until Edit Package is active");
assert.match(packagesHtml,/total planned minimum/);
assert.doesNotMatch(packagesHtml,/packageRules syllabiRules" open/,"Focused Package may open, but Syllabi must remain collapsed until requested");
assert.match(packagesHtml,/Assessment criteria/);
assert.match(packagesHtml,/Emergency requirements/);
assert.match(packagesHtml,/data-global-add-open="syllabi"/);
assert.match(packagesHtml,/data-global-add-panel="syllabi" hidden/);
assert.match(packagesHtml,/data-global-add-cancel="syllabi"/);
assert.match(packagesHtml,/data-global-add="syllabi"/);
assert.match(packagesHtml,/data-global-add="criteria"/);
assert.match(packagesHtml,/data-global-add="emergencies"/);
assert.match(packagesHtml,/data-global-add="counters"/);
assert.match(packagesHtml,/data-global-add="exams"/);
assert.match(packagesHtml,/data-global-add="progression"/);
assert.match(packagesHtml,/packageFocused/);
assert.doesNotMatch(packagesHtml,/packageEditing/,"Focused Package is view mode until Edit is selected");
vm.runInContext("state.packageEditId='ui_custom_package';render()",context);
const editingPackageHtml=elements.get("#content").innerHTML;
assert.match(editingPackageHtml,/packageEditing/);
assert.match(editingPackageHtml,/Done editing/);
assert.match(editingPackageHtml,/Delete Package/);
assert.match(editingPackageHtml,/data-delete-package="ui_custom_package"/,"Delete Package must appear after Edit Package is selected");
assert.match(editingPackageHtml,/data-global-package-id="ui_custom_package"[\s\S]*?<fieldset class="packageEditFieldset" >/,"The selected Package editor must be enabled while editing");
vm.runInContext("FLYMPUS_TRAINING.saveGlobalOverrides('ep_full_day_new',{syllabi:{full_intro:{applicable:false}}});state.packageFocusId='ep_full_day_new';state.packageEditId='ep_full_day_new';render()",context);
const excludedSyllabusHtml=elements.get("#content").innerHTML;
assert.match(excludedSyllabusHtml,/Excluded syllabi \(<span data-excluded-syllabus-count>1<\/span>\)/);
assert.match(excludedSyllabusHtml,/data-restore-syllabus="full_intro"/);
assert.match(excludedSyllabusHtml,/data-syllabus-row="full_intro"[\s\S]*?syllabusExcludedRow|syllabusExcludedRow[\s\S]*?data-syllabus-row="full_intro"/);
assert.match(excludedSyllabusHtml,/data-syllabus-row="full_positions_a"[\s\S]*?<span class="syllabusOrderNumber">2<\/span>/,"Active syllabus order must close the gap when Introduction is excluded");
assert.match(excludedSyllabusHtml,/Only active syllabi are numbered/);
vm.runInContext("FLYMPUS_TRAINING.saveGlobalOverrides('ep_full_day_new',{});state.packageFocusId='ui_custom_package';state.packageEditId='ui_custom_package';render()",context);
vm.runInContext("FLYMPUS_TRAINING.saveGlobalOverrides('ep_full_refresh',{custom:{syllabi:[{id:'ui_pkg_syll',name:'Reusable Package Syllabus',order:99,minimum:1,mode:'INSTRUCTED',instructorRequired:true,track:'day'}],criteria:[{id:'ui_pkg_criterion',name:'Reusable Package Criterion',weight:10}],emergencies:[{id:'ui_pkg_emergency',name:'Reusable Package Emergency',category:'General / Operational'}]},emergencyRequirementIds:['ui_pkg_emergency']});render()",context);
assert.match(elements.get("#content").innerHTML,/Reusable Package Syllabus/);
assert.match(elements.get("#content").innerHTML,/Reusable Package Criterion/);
assert.match(elements.get("#content").innerHTML,/Reusable Package Emergency/);
assert.match(elements.get("#content").innerHTML,/PACKAGE CUSTOM/);
vm.runInContext("FLYMPUS_TRAINING.saveGlobalOverrides('ep_full_refresh',{});FLYMPUS_TRAINING.removeCustomPackage('EP','ui_custom_package');state.settingsTab='catalog';state.typeWorkspace='IP';render()",context);
assert.match(elements.get("#content").innerHTML,/Control-station configuration/);
assert.doesNotMatch(elements.get("#content").innerHTML,/globalPackageForm/);
vm.runInContext("state.typeWorkspace='TECHNICIAN';render()",context);
assert.match(elements.get("#content").innerHTML,/System configuration/);
assert.match(elements.get("#content").innerHTML,/Engine H \/ GCS-D/);
vm.runInContext("state.settingsTab='packages';state.packageWorkspace='TECHNICIAN';render()",context);
assert.match(elements.get("#content").innerHTML,/TECHNICIAN Training Packages/);
vm.runInContext("FLYMPUS_TRAINING.saveGlobalOverrides('tech_full_new',{program:{name:'Global Technician Package'}});render()",context);
assert.match(elements.get("#content").innerHTML,/Global Technician Package/);
assert.match(elements.get("#content").innerHTML,/EDITED DEFAULT/);
vm.runInContext("FLYMPUS_TRAINING.saveGlobalOverrides('tech_full_new',{})",context);
vm.runInContext("Object.assign(currentCourseMeta,{type:'TECHNICIAN',phase:'Full Scale',platformId:'aerostar',trainingKind:'New Training',dayNight:'Mixed \/ Day+Night',country:'Israel',programId:'tech_full_new'});state.screen='profile';state.profileTab='activity';render()",context);
assert.match(elements.get("#content").innerHTML,/Practical experience/);
assert.match(elements.get("#content").innerHTML,/Record practical task/);
assert.match(elements.get("#content").innerHTML,/Engine Installation \/ Removal/);
assert.match(elements.get("#content").innerHTML,/name="quantity" type="number" min="1" step="1"/);
console.log(JSON.stringify({ok:true,myCourses:true,multiCourse:true,courseIsolation:true,instructorAssignments:true,home:true,settings:true,directPackageCourseCreation:true,createCourseValidation:true,uniqueCourseCode:true,trainingPackages:true,separatePackagesPage:true,sectorPackageAssignment:true,suggestedPackageName:true,fullPackageEditor:true,collapsedPackageEditor:true,compactSyllabusTable:true,dragSyllabusOrdering:true,smoothDragAnimation:true,compactAddRows:true,activeOrderReindex:true,excludedSyllabusRestore:true,packageEditMode:true,packageDelete:true,editOnlyPackageDelete:true,globalPackageCustomItems:true,globalPackagePath:true,globalPackageDefaults:true,coursePackageOverride:true,courseOnlyItems:true,professionContext:true,advancedOrder:true,customPlatforms:true,overrides:true,rosterMembership:true,experienceUx:true,technicianExperience:true}));
