const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..');
const output=path.join(root,'dist');
const publicFiles=['index.html','auth.js','auth.css','firebase-config.js','storage-scope.js',
  'theme-controller.js','sw.js','manifest.webmanifest','push-config.json'];
// Only reviewed public assets enter Hosting. Auth credentials generated by CI,
// tests, Firestore rules and the optional push server stay outside this bundle.
for(const file of publicFiles)fs.accessSync(path.join(root,file));
fs.rmSync(output,{recursive:true,force:true});
fs.mkdirSync(output,{recursive:true});
for(const file of publicFiles)fs.copyFileSync(path.join(root,file),path.join(output,file));
fs.cpSync(path.join(root,'assets'),path.join(output,'assets'),{recursive:true});
const commit=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();
const files={};
function record(directory){
  for(const entry of fs.readdirSync(directory,{withFileTypes:true})){
    const filename=path.join(directory,entry.name);
    if(entry.isDirectory())record(filename);
    else files[path.relative(output,filename).split(path.sep).join('/')]=crypto.createHash('sha256').update(fs.readFileSync(filename)).digest('hex');
  }
}
record(output);
fs.writeFileSync(path.join(output,'deploy-info.json'),JSON.stringify({commit,files},null,2)+'\n');
console.log(`Prepared ${Object.keys(files).length} public files from ${commit}`);
