const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');
const {buildFromWorkflowRun,stampReleaseHtml}=require('./release-build.cjs');
const root=path.resolve(__dirname,'..');
const output=path.join(root,'dist');
// A release manifest must never attribute uncommitted source to a clean SHA.
const changes=execFileSync('git',['status','--porcelain','--untracked-files=normal'],{cwd:root,encoding:'utf8'}).trim();
if(changes)throw new Error('Hosting bundle requires a complete committed, clean source checkout');
const head=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();
if(process.env.GITHUB_SHA&&process.env.GITHUB_SHA!==head)throw new Error('Checkout differs from approved CI commit');
execFileSync(process.execPath,[path.join(__dirname,'sync-theme-bootstrap.cjs'),'--check'],{cwd:root,stdio:'inherit'});
const publicFiles=['index.html','auth.js','auth.css','account-switcher.js','firebase-config.js','storage-scope.js',
  'theme-controller.js','sw.js','manifest.webmanifest','push-config.json'];
// Only reviewed public assets enter Hosting. Auth credentials generated by CI,
// tests, Firestore rules and the optional push server stay outside this bundle.
for(const file of publicFiles)fs.accessSync(path.join(root,file));
fs.rmSync(output,{recursive:true,force:true});
fs.mkdirSync(output,{recursive:true});
for(const file of publicFiles)fs.copyFileSync(path.join(root,file),path.join(output,file));
fs.cpSync(path.join(root,'assets'),path.join(output,'assets'),{recursive:true});
const commit=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();
if(!/^[a-f0-9]{40}$/.test(commit))throw new Error('Invalid Git commit for deployment');
const build=buildFromWorkflowRun(process.env.GITHUB_RUN_NUMBER);
/* Stamp every Firebase deployment with its actual commit. A constant source
   worker version made iOS continue serving an older Safety interface. */
const workerPath=path.join(output,'sw.js');
const workerSource=fs.readFileSync(workerPath,'utf8');
const workerPattern=/const FLYMPUS_SW_VERSION='[^']+';/;
if(!workerPattern.test(workerSource))throw new Error('Missing Service Worker version constant');
fs.writeFileSync(workerPath,workerSource.replace(workerPattern,
  "const FLYMPUS_SW_VERSION='"+commit.slice(0,16)+"';"));
const htmlPath=path.join(output,'index.html');
const htmlSource=fs.readFileSync(htmlPath,'utf8');
fs.writeFileSync(htmlPath,stampReleaseHtml(htmlSource,commit,build));
const files={};
function record(directory){
  for(const entry of fs.readdirSync(directory,{withFileTypes:true})){
    const filename=path.join(directory,entry.name);
    if(entry.isDirectory())record(filename);
    else files[path.relative(output,filename).split(path.sep).join('/')]=crypto.createHash('sha256').update(fs.readFileSync(filename)).digest('hex');
  }
}
record(output);
fs.writeFileSync(path.join(output,'deploy-info.json'),JSON.stringify({commit,build,files},null,2)+'\n');
console.log(`Prepared Build ${build}: ${Object.keys(files).length} public files from ${commit}`);
